//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int ID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DepartmentDetailID { get; set; }
        public Nullable<int> FacultyID { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Department Department2 { get; set; }
        public virtual Department Department11 { get; set; }
        public virtual Department Department3 { get; set; }
        public virtual DepartmentDetail DepartmentDetail { get; set; }
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
    }
}
