//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndividualDetail()
        {
            this.Individual = new HashSet<Individual>();
        }
    
        public int ID { get; set; }
        public string IdentificationNumber { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> PhoneNumberID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> PostCodeID { get; set; }
        public Nullable<int> EMailID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
        public virtual EMail EMail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Individual> Individual { get; set; }
        public virtual IndividualDetail IndividualDetail1 { get; set; }
        public virtual IndividualDetail IndividualDetail2 { get; set; }
        public virtual IndividualDetail IndividualDetail11 { get; set; }
        public virtual IndividualDetail IndividualDetail3 { get; set; }
        public virtual IndividualDetail IndividualDetail12 { get; set; }
        public virtual IndividualDetail IndividualDetail4 { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual PhoneNumber PhoneNumber { get; set; }
        public virtual PostCode PostCode { get; set; }
    }
}
