//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentInformationSystemDatabaseEntities1 : DbContext
    {
        public StudentInformationSystemDatabaseEntities1()
            : base("name=StudentInformationSystemDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DepartmentDetail> DepartmentDetail { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<EMail> EMail { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<FacultyDetail> FacultyDetail { get; set; }
        public virtual DbSet<Individual> Individual { get; set; }
        public virtual DbSet<IndividualDetail> IndividualDetail { get; set; }
        public virtual DbSet<Nationality> Nationality { get; set; }
        public virtual DbSet<PhoneNumber> PhoneNumber { get; set; }
        public virtual DbSet<PostCode> PostCode { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentDetail> StudentDetail { get; set; }
    }
}
