//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public Nullable<int> IndividualID { get; set; }
        public string StudentNumber { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<int> StudentDetailID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Individual Individual { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual Student Student2 { get; set; }
        public virtual Student Student11 { get; set; }
        public virtual Student Student3 { get; set; }
        public virtual Student Student12 { get; set; }
        public virtual Student Student4 { get; set; }
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
